language: android
jdk: oraclejdk8
sudo: required

android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-27.0.3
    - android-27
    - extra-google-m2repository
    - extra-android-m2repository

script:
 - ./gradlew build
 - ./gradlew test

before_install:
 - chmod +x gradlew

after_success:
  - python <(curl -s https://raw.githubusercontent.com/TouK/sputnik-ci/master/sputnik-ci.py)
